"""Optional, observational lifecycle hooks for a V1 Agent run."""
from __future__ import annotations

from typing import Protocol


class AgentHooks(Protocol):
    """Implement any subset of these sync or async methods.

    Hooks are observational only.  Their failures are logged and never affect
    scheduling, transcript commits, or the terminal result.
    """

    def on_run_start(self, run_context: object) -> object: ...
    def on_run_end(self, result: object) -> object: ...
    def on_turn_start(self, run_context: object) -> object: ...
    def on_turn_end(self, run_context: object) -> object: ...
    def on_model_start(self, model_context: object) -> object: ...
    def on_model_end(self, message: object) -> object: ...
    def on_tool_start(self, call: object) -> object: ...
    def on_tool_end(self, outcome: object) -> object: ...
