"""Local native audio I/O contracts."""
from __future__ import annotations

from typing import Protocol

from ..types import AudioChunk


class AudioInput(Protocol):
    async def start(self) -> None: ...
    async def read(self) -> AudioChunk: ...
    async def close(self) -> None: ...


class AudioOutput(Protocol):
    async def start(self) -> None: ...
    async def write(self, audio: AudioChunk) -> None: ...
    async def clear(self) -> None: ...
    async def close(self) -> None: ...
